config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', :omniauth_callbacks => "omniauth_callbacks"}
  resources :users, only: [:show]
  root to: "articles#index"
  resources :articles, only: [:index,:create] do
    resources :comments, only: [:index,:edit,:update,:new,:create,:destroy] do
      resources :replies, only: [:edit,:create,:update,:destroy,:delete]
    end
  end
  resources :subscriptions
  get '/max', to: 'articles#show'
  match '*path' => 'application#fallback', via: :all
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :article
    belongs_to :user
    has_many :replies, dependent: :delete_all

    validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
        before_action :find_comment, only: [:edit,:update,:destroy]
        before_action :find_article, only: [:new,:create,:index,:edit,:update,:destroy]
        before_action :bad_sources, only: [:index,:create]
        before_action :article_exists?, only: [:new,:edit]
        before_action :comment_exists?,:authenticate_user_of_comment, only: [:edit]
        
        def new
            
            @comment = Comment.new
        end
    
        def create
            @comment = Comment.new(comment_params)
           @reply = Reply.new
            if !current_user
                flash[:error] = "You must be logged in to make a new comment."
                redirect_to new_user_session_path
            elsif
                @comment.user_id = current_user.id
                @comment.article_id = @article.id
                    if  @comment.save
                        redirect_to article_comments_path(@article)
                    else
                        render '/comments/index'
                    end
            end
        end

        # If you add _path or _url to any of the names under "Prefix", you'll have the helper for that route. ex.) author_post_path(author_id, post_id)
        def index
            if @article
                @comment = Comment.new
                @reply = Reply.new
            else
              redirect_to articles_path
            end
        end
    
        def edit
        end
    
        def update
            if @comment.update(comment_params)
                redirect_to article_comments_path(@article)
            else
                render :edit          
            end
        end
    
        def destroy
            @comment.delete
            redirect_to article_comments_path(@article)
        end

        private

        def find_comment
            @comment = Comment.find_by_id(params[:id])
        end
    
        def comment_params
            params.require(:comment).permit(:content, :article_id)
        end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<%= render partial: '/partials/article', locals:{article: @article, descritpion_length: 500, pathing:@article.url }%>
<%= render partial: '/partials/form', locals:{comment: @comment, article: @article, submit_text: 'Edit Comment' }%>

app/views/comments/index.html.erb
<% if !@bad_sources.include?(@article.source)%>
    <div class="embed-responsive embed-responsive-0by0 container-flex">
        <iframe class="embed-responsive-item" src="<%=@article.url%>"></iframe>
    </div>
    <% else %>
        <%=render partial: '/partials/article', locals: {article: @article, descritpion_length: 500,pathing:@article.url}%>
<% end %>

<%= link_to 'Requirment Satisfaction', new_article_comment_path(@article) %>

<%=render partial: '/partials/form', locals: {comment: @comment, article: @article, submit_text: "Submit Comment"}%><br>

<%= render partial: '/partials/comments', locals:{article: @article}%>

app/views/comments/new.html.erb
<%=render partial: '/partials/form', locals: {comment: @comment, article: @article, submit_text: "Submit Comment"}%><br>