config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', :omniauth_callbacks => "omniauth_callbacks"}
  resources :users, only: [:show]
  root to: "articles#index"
  resources :articles, only: [:index,:create] do
    resources :comments, only: [:index,:edit,:update,:new,:create,:destroy] do
      resources :replies, only: [:edit,:create,:update,:destroy,:delete]
    end
  end
  resources :subscriptions
  get '/max', to: 'articles#show'
  match '*path' => 'application#fallback', via: :all
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/partials/_article.html.erb
<div class="col-md-10 container">
      <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary">News</strong>
          <h5 class="mb-0"><%=article.title%></h5>
          <div class="mb-1 text-muted"><%=article.published_at%></div>
          <p class="card-text mb-auto"><%=article.description.first(descritpion_length)%></p>
          <%=link_to "Continue reading...", pathing, class:"stretched-link"%>
        </div>
        <div class="col-auto d-none d-lg-block">
          <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em"><%=article.source%></text></svg>
        </div>
      </div>
    </div>

app/views/partials/_comments.html.erb
    <div class="card">
                <h3 class="text-center "> Comments: </h3>
<%article.comments.each do |comment| %>
        <div class="container mb-5 mt-5">
    <div class="card">
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-12">
                        <div class="media"> <img class="mr-3 rounded-circle" alt="Bootstrap Media Preview" src="https://techcrunch.com/wp-content/uploads/2015/09/11667534_10102203860243201_2713296330820668368_n.jpg?w=528" />
                            <div class="media-body">
                                <div class="row">
                                    <div class="col-8 d-flex">
                                        <h5><%=comment.user.username%></h5>
                                    </div>
                                </div>
                                <%= comment.content%> 
                                <% if !current_user %><br>
                                    <%=""%>
                                    <% elsif current_user.id == comment.user_id%>
                                    <%= link_to 'Delete', article_comment_path(article, comment),class:"btn btn-ssm btn-outline-secondary", method: :delete, data:{Confirm: "Delete?"}%> 
                                    <%= link_to 'Edit', edit_article_comment_path(article, comment),class:"btn btn-ssm btn-outline-secondary"%>
                                <%end%>
                                <div class="media mt-4"> <a class="pr-3" href="#"><img class="rounded-circle" alt="Bootstrap Media Another Preview" src="https://cdn.pixabay.com/photo/2017/06/13/12/53/profile-2398782_1280.png" /></a>
                                <%= render partial: '/partials/replies', locals:{article: @article, comment: comment}%>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
                                <div class="d-flex justify-content-center pt-3 pb-2">
                                <%= render partial: '/partials/rform', locals: {reply: @reply, comment: comment, article: @article}%>
                                </div>

        <%end%>
</div>

app/views/partials/_errors.html.erb
 <% if instance.errors.any? %>
   <div id="error_explanation">
    <h4>Error:</h4>
     <ul>
       <% instance.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
     </ul>
   </div>
 <% end %>
 <%=flash[:error2]%>

app/views/partials/_filter.html.erb
<div>
  <%= form_tag("/articles", method: "get") do %>
    <%= label_tag("Filter Source")%>
    <%= select_tag "source", options_for_select(Article.all_sources), include_blank: true, class:"custom-select custom-select-lg mb-3",onchange:'if(this.value != 0) { this.form.submit(); }'%>
  <% end %>
</div>

app/views/partials/_form.html.erb
<div class="form-floating container">
  <%=form_for [article,comment] do |f|%>

 <%=render partial: '/partials/errors', locals:{instance:comment}%>

    
  <div class="field<%= ' field_with_errors' if comment.errors[:content].any? %>">
    <%=f.label :content, 'Comment:'%><br>
    <%=f.text_area :content, class:"form-control addtxt container", placeholder:"Leave a comment here",  style:"height: 100px; width: 2000px;" %><br>
    <%=f.submit submit_text ,class:"btn btn-lg btn-outline-secondary" %>
  </div>
  <%end%>
  
</div>

app/views/partials/_index_articles.html.erb
<div class="col-md-6">
      <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary"><%=article.source%></strong>
          <h5 class="mb-0"><%=article.title%></h5>
          <div class="mb-1 text-muted"><%=article.published_at%></div>
          <p class="mb-auto"><%=article.description.first(90)%></p>
          <%=link_to "Continue reading...", article_comments_path(article), class:"stretched-link"%>
        </div>
        <div class="col-auto d-none d-lg-block">
          <svg class="bd-placeholder-img" width="125" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em"></text></svg>
        </div>
      </div>
    </div>

app/views/partials/_replies.html.erb
       
<% comment.replies.each do |reply| %>
<div class="media-body">
    <div class="row">
        <div class="col-12 d-flex">
            <h5><%=reply.user.username%></h5>
        </div>
    </div> 
    <%= reply.content%> <br>
    <%if !current_user%>
<%=""%>
    <% elsif current_user.id == reply.user.id%>
                <%=link_to "Edit Reply", edit_article_comment_reply_path(article, comment, reply),class:"btn btn-ssm btn-outline-secondary"%> 
                <%=link_to "Delete Reply",article_comment_reply_path(article, comment, reply) , method: :delete,  data:{Confirm: "Delete?"},class:"btn btn-ssm btn-outline-secondary"%>
                <%end%>
            <%end%>
</div>

app/views/partials/_rform.html.erb
<%=form_for [article, comment, reply] do |f|%>
<%=render partial: '/partials/errors', locals:{instance:@reply}%>
<div class="field<%= ' field_with_errors' if reply.errors[:content].any? %>">
  
    <%=f.text_area :content, placeholder:"Add a reply", class: "form-control addtxt" %>
    <%f.submit %>
      <button class="btn btn-sm btn-outline-secondary" style="padding-top:1px;" >
          <span>Reply</span>
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-chat-fill" viewBox="0 0 16 16" >
            <path d="M8 15c4.418 0 8-3.134 8-7s-3.582-7-8-7-8 3.134-8 7c0 1.76.743 3.37 1.97 4.6-.097 1.016-.417 2.13-.771 2.966-.079.186.074.394.273.362 2.256-.37 3.597-.938 4.18-1.234A9.06 9.06 0 0 0 8 15z" ></path>
          </svg>
      </button>
  <%end%>
</div>

app/views/partials/_search.html.erb
  <%= form_tag("/articles", method: "get") do %>
  
    <%= text_field_tag :query %>
    <%= submit_tag "search",data: { disable_with: false }%>
    <% end %>